### PR TITLE
feat: add astro example

### PR DESCRIPTION
**Pull request by barbados-clemens**
adds a simple astro site with a `@nx/js:lib` project to hold reusable components. add simple playwright tests for basic validation.

### CODE REVIEW

**Comment by ndcunningham** [comment]
Should this be called `astro-standalone`? Since it doesn't use `integrated`

**Comment by barbados-clemens** [comment]
> Should this be called `astro-standalone`, since it is not an `integrated` workspace?


if that's the new standard then we can sure. 

would need to rename a handful of other repos as well IIRC.

**Comment by Coly010** [comment]
Does this example need a project-graph plugin like this: https://github.com/nxtensions/nxtensions/blob/main/packages/astro/src/project-graph/plugin.ts ?

**Comment by barbados-clemens** [comment]
> Does this example need a project-graph plugin like this: [nxtensions/nxtensions@`main`/packages/astro/src/project-graph/plugin.ts](https://github.com/nxtensions/nxtensions/blob/main/packages/astro/src/project-graph/plugin.ts?rgh-link-date=2023-07-26T08%3A43%3A40Z) ?

I didn't want to make a graph plugin for such a simple workspace esp when the desired result can be achieved with just using the `implicitDependencies`. Focusing on the simplicity of a standalone workspace and it only applies to .astro files. most of the libraries being created would end up being things nx already understands to parse such a jsx/ts files.

**Pull request merged**
